export const NAV_TABS = [
  { id: 'edit', label: 'Edit Project' },
  { id: 'analytics', label: 'Analytics' },
  { id: 'task', label: 'Task' },
  { id: 'config', label: 'Config' },
  { id: 'users', label: 'Users' },
  { id: 'payments', label: 'Payment Settings' },
  { id: 'tests', label: 'Test' },
  { id: 'review', label: 'Review Stages' },
]

export const STATUS_FILTERS = [
  { id: 'open', label: 'Open' },
  { id: 'allocated', label: 'Allocated' },
  { id: 'ready', label: 'Ready to deliver' },
]

export const MOCK_TASKS = [
  {
    id: 'c9ba1ce630b4e76e1ecc347049f2a',
    displayId: 'c9ba1ce630b4e…',
    statusBucket: 'ready',
    taskStatus: 'COMPLETED',
    taskerPseudo: '-',
    taskerAllocation: 'isabel isabel',
    reviewerPseudo: '-',
    reviewAllocation: '-',
  },
  {
    id: '15310e70e44663709edaadc0704d',
    displayId: '15310e70e4466…',
    statusBucket: 'ready',
    taskStatus: 'COMPLETED',
    taskerPseudo: '-',
    taskerAllocation: 'Heena Inamdar',
    reviewerPseudo: '-',
    reviewAllocation: '-',
  },
  {
    id: '877410c48c55c49d915a178e29998',
    displayId: '877410c48c55c…',
    statusBucket: 'ready',
    taskStatus: 'COMPLETED',
    taskerPseudo: '-',
    taskerAllocation: 'christian duat',
    reviewerPseudo: '-',
    reviewAllocation: '-',
  },
  {
    id: 'fa836c0bb35462a9c064a91f813531',
    displayId: 'fa836c0bb3546…',
    statusBucket: 'ready',
    taskStatus: 'COMPLETED',
    taskerPseudo: '-',
    taskerAllocation: 'elsa.ubieto@gmail.com',
    reviewerPseudo: '-',
    reviewAllocation: '-',
  },
  {
    id: 'c7e9ecbbf5433224c9b79e50a91155',
    displayId: 'c7e9ecbbf5433…',
    statusBucket: 'ready',
    taskStatus: 'COMPLETED',
    taskerPseudo: '-',
    taskerAllocation: 'psico.susanagp@gmail.com',
    reviewerPseudo: '-',
    reviewAllocation: '-',
  },
  {
    id: '75a6522ba1b8131bbce8be1b689aa1',
    displayId: '75a6522ba1b81…',
    statusBucket: 'ready',
    taskStatus: 'COMPLETED',
    taskerPseudo: '-',
    taskerAllocation: 'Labimorogigs@gmail.com',
    reviewerPseudo: '-',
    reviewAllocation: '-',
  },
  {
    id: 'fa551f2420e53c8784754310f213d9',
    displayId: 'fa551f2420e53…',
    statusBucket: 'allocated',
    taskStatus: 'IN_PROGRESS',
    taskerPseudo: '-',
    taskerAllocation: 'isabel isabel',
    reviewerPseudo: '-',
    reviewAllocation: '-',
  },
  {
    id: 'a235ba354e339f81f9577a7747541',
    displayId: 'a235ba354e339…',
    statusBucket: 'allocated',
    taskStatus: 'IN_PROGRESS',
    taskerPseudo: '-',
    taskerAllocation: 'Heena Inamdar',
    reviewerPseudo: '-',
    reviewAllocation: '-',
  },
  {
    id: 'be01a454ba30ab34043dea130ef951',
    displayId: 'be01a454ba30a…',
    statusBucket: 'open',
    taskStatus: 'PENDING',
    taskerPseudo: 'FSLTest',
    taskerAllocation: '-',
    reviewerPseudo: '-',
    reviewAllocation: '-',
  },
  {
    id: 'b58c80b3609b0a13823315eec0d9a9',
    displayId: 'b58c80b3609b0…',
    statusBucket: 'open',
    taskStatus: 'PENDING',
    taskerPseudo: 'FSLTest',
    taskerAllocation: '-',
    reviewerPseudo: '-',
    reviewAllocation: '-',
  },
]

export const CONFIG_SUBTABS = [
  { id: 'task', label: 'Task' },
  { id: 'review_dummy_1', label: 'Review dummy' },
  { id: 'review_dummy_3', label: 'Review dummy 3' },
]

export const MOCK_CONFIGS = {
  task: [
    { order: 1, type: 'TASK', configType: 'Audio', required: true, value: 'Context Audio', identifier: 'context_audio' },
    { order: 2, type: 'TASK', configType: 'Paragraph', required: true, value: 'Conversation Context Text', identifier: 'context_text' },
    { order: 3, type: 'TASK', configType: 'Paragraph', required: true, value: 'Next Agent Response Text', identifier: 'response_text' },
    { order: 4, type: 'TASK', configType: 'Audio', required: true, value: 'Next Agent Response 1', identifier: 'response_1_audio' },
    { order: 5, type: 'TASK', configType: 'Audio', required: true, value: 'Next Agent Response 2', identifier: 'response_2_audio' },
    { order: 6, type: 'TASK', configType: 'Audio', required: true, value: 'Reference Voice Audio', identifier: 'reference_voice_audio' },
    { order: 7, type: 'TASK', configType: 'Radio', required: false, value: 'Discard', identifier: 'discarded' },
    { order: 8, type: 'TASK', configType: 'Radio', required: true, value: 'Rate the FAITHFULNESS of the Response 1', identifier: 'R1_faithful_rating' },
    { order: 9, type: 'TASK', configType: 'Radio', required: true, value: 'Rate the FAITHFULNESS of the Response 2', identifier: 'R2_faithful_rating' },
    { order: 10, type: 'TASK', configType: 'Radio', required: true, value: 'Rate the EXPRESSIVENESS of the Response 1', identifier: 'R1_expressive_rating' },
  ],
  review_dummy_1: [
    { order: 1, type: 'REVIEW', configType: 'Checkbox', required: true, value: 'Grammar quality', identifier: 'grammar_quality' },
    { order: 2, type: 'REVIEW', configType: 'Checkbox', required: false, value: 'Pronunciation', identifier: 'pronunciation' },
  ],
  review_dummy_3: [
    { order: 1, type: 'REVIEW', configType: 'Textarea', required: true, value: 'Reviewer Notes', identifier: 'reviewer_notes' },
  ],
}
