version: "3.9"

services:
  backend:
    build: .
    container_name: Dhriti_ai-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: Dhriti_ai-db
    restart: always
    environment:
      POSTGRES_USER: Dhriti_ai
      POSTGRES_PASSWORD: Dhriti_ai123
      POSTGRES_DB: Dhriti_ai_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
